### ISSUE TITLE
When setting map extent 'fit=true' should be default.

### ISSUE THREAD

**Issue by DavidSpriggs** [Esri/arcgis-dijit-home-button-js#1]
This becomes an issue, and I discovered it, when setting the home button's extent to the extent of a poly feature. The poly feature will not always be completely in view unless `fit` is set to `true`.

line 115 is the issue:

``` javascript
this.map.setExtent(defaultExtent).then(lang.hitch(this, function(){...
```

see: https://github.com/driskull/arcgis-dijit-home-button-js/blob/master/js/HomeButton.js#L115

To fix, make this an optional param, with default of true:

Add a member var called fit: `fit: true`
then on line 115:

``` javascript
this.map.setExtent(defaultExtent, this.fit).then(lang.hitch(this, function(){...
```

**Comment by bweisberg** [comment]
I'm curious about [setExtent fit='true'](https://developers.arcgis.com/javascript/jsapi/map-amd.html#setextent) and found this issue discussing it.  When should I use fit='true'?  My reading here is to use the default fit='false' when we're setting the extent to another extent, but probably use fit='true' to be sure all features are in view.

**Comment by driskull** [comment]
the default is false. In 4.0, it's true by default I think. The option is gone.

It just makes the whole extent fit into the view of the map.
